spring:
  application:
    name: user-center-ding
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/usermanager
server:
  port: 8080
  servlet:
    context-path: /api
    session:
      timeout: 86400
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
  global-config:
    db-config:
      logic-delete-field: isDelete #全局删除的实体字段名（）
      logic-delete-value: 1  #逻辑已经删除默认值
      logic-not-delete-value: 0  #逻辑未删除值（默认0）
